### ISSUE TITLE
USWDS 2.x support?

### ISSUE THREAD

**Issue by ConnorDY** [department-of-veterans-affairs/veteran-facing-services-tools#504]
Is there any plan to update formation to use USWDS 2.0+?
The last USWDS 1.x release was over a year ago now and is no longer being supported as far as I'm aware.

**Comment by cvalarida** [comment]
Hey, @ConnorDY! Thanks for dropping us a line.

We investigated this a while back and discovered it'd be a _lot_ of work to migrate USWDS from 1.x to 2.x. I forget what all the reasons were for choosing to not upgrade yet, but at the time, we didn't have the resources.

That said, making the upgrade is definitely something we've been thinking about of late, but it's not high on our list of priorities right now.

Have you run into any issues because we're using USWDS v1?

**Comment by ConnorDY** [comment]
I am not currently using formation but a project I am a part of has expressed interesting in using it.
There are many new components that have been added and are continuing to be added in USWDS v2 that do not exist in v1 and we would miss out on these plus future support if we chose to use the v1 based formation.

**Comment by ncksllvn** [comment]
@cvalarida There is a section on design.va.gov about USWDS v2 -> https://design.va.gov/documentation/#us-web-design-system-already-included

> 
> We’re not currently updating to USWDS v2 because:
> 
> Many of the naming conventions have changed between the 2 versions.
> The design of some of the base components has changed based on specific needs for VA.gov.
> Formation includes its own set of utility classes and design tokens.

Like @ConnorDY said though, it would be really cool if VADS were using the latest version (or only as a foundational building block and not actually visible to the end developer.)

**Comment by cvalarida** [comment]
Ahhh, that's good to know! Thanks for that context, @ncksllvn. One of these days, I'll get around to reading all that's on that site. :sweat_smile:

Upgrading to USWDS v2 would be cool, but unless we're encountering problems with using v1 as our base, prioritizing that effort over everything else we have to do is a hard sell. It sounds like a lot of work and the gain is unclear.

Making that upgrade has been on our radar. Turns out we didn't have a ticket to do that discovery yet, so I just wrote one. I'm closing in favor of [this discovery ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16523) to get a better understanding of the level of effort and benefit we'll gain.
